// Generated by CoffeeScript 1.4.0
(function() {
  var Card, card;

  Card = (function() {

    function Card(index) {
      this.index = index;
    }

    Card.prototype.suit = function() {
      return this.index / 4;
    };

    Card.prototype.rank = function() {
      return this.index % 13;
    };

    return Card;

  })();

  card = new Card(14);

  console.log(card.suit);

  console.log(card.rank);

}).call(this);
