// Generated by CoffeeScript 1.4.0
(function() {
  var browser, handleCommand, makeRequest, mdns, readline, request, rl, servers;

  mdns = require('mdns');

  request = require('request');

  readline = require('readline');

  makeRequest = function(server, params) {
    var options;
    if (params == null) {
      params = {};
    }
    console.log('making request');
    options = {
      uri: "http://" + server.host + ":" + server.port + "/url",
      json: params
    };
    return request.post(options, function(error, response, body) {
      console.log(error);
      return console.log(body);
    });
  };

  handleCommand = function(command) {
    var params;
    params = {
      command: command
    };
    return makeRequest(servers['BigScreen@rinzler.local'], params);
  };

  browser = mdns.createBrowser(mdns.tcp('http'));

  servers = {};

  browser.on('serviceUp', function(service) {
    console.log('service up: ', service);
    return servers[service.name] = service;
  });

  browser.on('serviceDown', function(service) {
    console.log('service down: ', service.name);
    return delete servers[service.name];
  });

  browser.start();

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  rl.setPrompt('> ', 2);

  rl.prompt();

  rl.on("line", function(line) {
    handleCommand(line.trim());
    return rl.prompt();
  });

}).call(this);
