// Generated by CoffeeScript 1.4.0
(function() {
  var ad, app, exec, express, handleCommand, mdns, os, puts, sys;

  mdns = require('mdns');

  express = require('express');

  sys = require('sys');

  exec = require('child_process').exec;

  os = require('os');

  puts = function(error, stdout, stderr) {
    return sys.puts(stdout);
  };

  handleCommand = function(command) {
    return exec("open " + command, puts);
  };

  ad = mdns.createAdvertisement(mdns.tcp('http'), 4321, {
    name: "BigScreen@" + (os.hostname())
  });

  ad.start();

  app = express();

  app.use(express.json());

  app.post('/url', function(req, res) {
    return handleCommand(req.body.command);
  });

  app.post('/play', function(req, res) {
    return handleCommand(req.body.command);
  });

  app.post('/open', function(req, res) {
    return handleCommand(req.body.command);
  });

  app.listen(4321);

}).call(this);
