// Generated by CoffeeScript 1.4.0
(function() {
  var ad, app, express, mdns;

  mdns = require('mdns');

  express = require('express');

  ad = mdns.createAdvertisement(mdns.tcp('http'), 4321);

  ad.start();

  app = express();

  app.use(express.json());

  app.get('/', function(req, res) {
    var body;
    body = 'Hello!';
    res.setHeader("Content-Type", "text/plain");
    res.setHeader("Content-Length", body.length);
    res.end(body);
    return console.log(req);
  });

  app.post('/command', function(req, res) {
    return console.log(req.body.command);
  });

  app.listen(4321);

}).call(this);
